/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package multicast.cliente.gui;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.*;
import java.util.*;
import java.util.Iterator;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import multicast.cliente.HiloPrincipal;

/**
 *
 * @author dapelle
 */
public class JFrameMain extends javax.swing.JFrame {

    private LinkedList<String> listaDirectorios;
    private JTextArea JTextAreaLog;

    /**
     * Creates new form JFrameMain
     */
    public JFrameMain() {
        initComponents();
        listaDirectorios = new LinkedList();
        jButtonSend.setEnabled(false);
        // Creamos la ventana de log
        JTextAreaLog = new JTextArea(20, 40);
        JTextAreaLog.setBackground(Color.BLACK);
        JTextAreaLog.setForeground(Color.WHITE);
        jPanel1.add(JTextAreaLog, "log");
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/multicast/gfx/plug_lan.png"));
        setIconImage(icon);
        
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTreeDir = new javax.swing.JTree();
        jPanel2 = new javax.swing.JPanel();
        jButtonAdd = new javax.swing.JButton();
        jButtonRemove = new javax.swing.JButton();
        jButtonSend = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Multicast versión 1.0");

        jPanel1.setLayout(new java.awt.CardLayout());

        jTreeDir.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("vacío");
        jTreeDir.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jTreeDir);

        jPanel1.add(jScrollPane1, "card2");

        jPanel2.setLayout(new java.awt.GridLayout(4, 1, 50, 10));

        jButtonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multicast/gfx/add.png"))); // NOI18N
        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAdd);

        jButtonRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multicast/gfx/remove.png"))); // NOI18N
        jButtonRemove.setText("Remove");
        jButtonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonRemove);

        jButtonSend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multicast/gfx/send.png"))); // NOI18N
        jButtonSend.setText("Send");
        jButtonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSend);

        jButtonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multicast/gfx/exit.png"))); // NOI18N
        jButtonSalir.setText("Exit");
        jButtonSalir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSalir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnVal = fileChooser.showOpenDialog(null);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            // Añadimos elementos
            listaDirectorios.add(file.getPath());
            cargaNodos();

        }


    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveActionPerformed
        try {
            String aux = jTreeDir.getSelectionPath().getLastPathComponent().toString();
            if (!aux.isEmpty()) {
                listaDirectorios.remove(aux);
                cargaNodos();
            }
        } catch (Exception e) {

        }

    }//GEN-LAST:event_jButtonRemoveActionPerformed

    public String cargaDirectorios() {
        StringBuilder sb = new StringBuilder();

        for (Iterator<String> iterator = listaDirectorios.iterator(); iterator.hasNext();) {
            sb.append(iterator.next());
        }
        return sb.toString();
    }

    public JTextArea getJTextAreaLog() {
        return JTextAreaLog;
    }


    private void jButtonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendActionPerformed
        jButtonAdd.setEnabled(false);
        jButtonRemove.setEnabled(false);
        jButtonSend.setEnabled(false);

        CardLayout layout = (CardLayout) jPanel1.getLayout();
        layout.show(jPanel1, "log");
        Thread hp = new HiloPrincipal(listaDirectorios, this);
        hp.start();

        // Llamada al sistema que empaqueta y envia con udp-send
//        String s = null;
//        String comando = "tar -cvf nombre-archivo.tar " + cargaDirectorios();        
//        System.out.println("" + comando);
//        try {
//
////            // Determinar en qué SO estamos
////            String so = System.getProperty("os.name");
////            String comando;
////            // Comando para Linux
////            if (so.equals("Linux")) {
////                comando = "ifconfig";  String next = iterator.next();
////            } // Comando para Windows
////            else {
////                comando = "ipconfig";
////            }
//
//            // Ejcutamos el comando
//            Process p = Runtime.getRuntime().exec(comando);
//
//            BufferedReader stdInput = new BufferedReader(new InputStreamReader(
//                    p.getInputStream()));
//
//            BufferedReader stdError = new BufferedReader(new InputStreamReader(
//                    p.getErrorStream()));
//
//            // Leemos la salida del comando
//            System.out.println("Ésta es la salida standard del comando:\n");
//            while ((s = stdInput.readLine()) != null) {
//                System.out.println(s);
//            }
//
//            // Leemos los errores si los hubiera
//            System.out.println("Ésta es la salida standard de error del comando (si la hay):\n");
//            while ((s = stdError.readLine()) != null) {
//                System.out.println(s);
//            }
//
//            System.exit(0);
//        } catch (IOException e) {
//            System.out.println("Excepción: ");
//            e.printStackTrace();
//            System.exit(-1);
//        }

    }//GEN-LAST:event_jButtonSendActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        //JOptionPane.showMessageDialog(this, "Multicast versión 0.9 \n\nColaboración realizada para el IES Comercio de Logroño\nDavid Pérez Lledó", "Acerca de Multicast...", JOptionPane.INFORMATION_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void cargaNodos() {
        String next;

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Directorios a enviar");
        for (Iterator<String> iterator = listaDirectorios.iterator(); iterator.hasNext();) {
            next = iterator.next();
            javax.swing.tree.DefaultMutableTreeNode treeNode = new javax.swing.tree.DefaultMutableTreeNode(next);
            treeNode1.add(treeNode);
        }

        jTreeDir.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        if (listaDirectorios.isEmpty()) {
            jButtonSend.setEnabled(false);
        } else {
            jButtonSend.setEnabled(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonRemove;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonSend;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTreeDir;
    // End of variables declaration//GEN-END:variables
}
